version: "3"
services:
  coloriral:
    image: coloriral
    ports:
      - "8080:8080"
    networks:
      - mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root 

networks:
  mysql: 
