version: "3"
services:
  coloriral:
    image: coloriral
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/testdb
    networks:
      - mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=cat
      - MYSQL_PASSWORD=1234

networks:
  mysql: 
